variables:
   DEBIAN_X86_BUILD_BASE_IMAGE: "debian/x86_build-base"
   DEBIAN_BASE_TAG: "2021-07-26-python"

   DEBIAN_X86_BUILD_IMAGE_PATH: "debian/x86_build"
   DEBIAN_BUILD_TAG: "2021-09-08-keep-gbm"

   DEBIAN_X86_TEST_BASE_IMAGE: "debian/x86_test-base"

   DEBIAN_X86_TEST_IMAGE: "debian/x86_test-base"
   DEBIAN_X86_TEST_GL_TAG: "2021-09-09-keep-wget"
   DEBIAN_X86_TEST_VK_TAG: "2021-07-30-piglit-2"


