[[deqp]]
deqp = "/usr/bin/strace"
renderer_check = "virgl.*llvmpipe"
version_check = "OpenGL ES 3.2 Mesa $VERSION"
caselists = ["/deqp/mustpass/gles3-master.txt"]
fraction = 1000
deqp_args = [
    "-s",
    "250",
    "-ff",
    "-tt",
    "-e",
    "%process,%signal",
    "-o",
    "/builds/tomeu/mesa/results/strace.log",
    "/install/crosvm-runner.sh",
    "/deqp/modules/gles3/deqp-gles3",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0
